import Head from "next/head";
import MainComponent from "../components/MainComponent";

export default function Home() {
  const newData = [
    {
      title: "Estimated owner refund",
      value: "$120.00*",
      children: [
        {
          title: "Total amount paid",
          value: "$250.00",
        },
        {
          title: "Booking fee",
          value: "$10.00",
        },
        {
          title: "Subtotal",
          value: "$240.00",
        },
        {
          title: "Sitter fee",
          value: "$120.00*",
        },
        {
          title: "Estimated owner refund",
          value: "$120.00*",
        },
      ],
    },
    {
      title: "Refund Method",
      value: "Paypal",
    },
  ];

  const data = [
    {
      title: "Estimated owner refund",
      value: "$120.00*",
      children: [
        {
          title: "Total amount paid",
          value: "$250.00",
        },
        {
          title: "Booking fee",
          value: "$10.00",
        },
        {
          title: "Subtotal",
          value: "$240.00",
        },
        {
          title: "Sitter fee",
          value: "$120.00*",
        },
        {
          title: "Estimated owner refund",
          value: "$120.00*",
        },
      ],
      lowerOuterLabel: "Refund Method",
      lowerOutervalue: "Paypal",
    },
  ];
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainComponent data={newData} />
    </div>
  );
}
